version: "2"

run:
  allow-parallel-runners: true

linters:
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    # - dupword # too noisy, little value
    - durationcheck
    - embeddedstructfieldcheck
    # - err113 # TODO: enable and fix
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - exhaustruct # prefer shorter struct literals
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    # - funlen # TODO: enable and fix
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    # - gocyclo # use cyclop instead
    - godot
    # - godox # TODO: enable and fix
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    # - mnd # TODO: enable and fix
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    # - nilnil # not bothered by nil val+err
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    # - nonamedreturns # prefer named returns in some cases
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    # - wrapcheck # TODO: enable and fix or user err113 instead
    # - wsl # use wsl_v5 instead
    - wsl_v5
    - zerologlint
  disable:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/gttelemetry/gran_turismo_telemetry.go
      - third_party$
      - builtin$
      - examples$
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - atomicgo.dev/keyboard
            - github.com/bwmarrin/discordgo
            - github.com/golang/freetype
            - github.com/gopxl/beep
            - github.com/gorilla/websocket
            - github.com/grafana/pyroscope-go
            - github.com/kennygrant/sanitize
            - github.com/rs/zerolog
            - github.com/spf13/viper
            - github.com/stretchr/testify
            - github.com/vwhitteron/simtezilo-dev
            - github.com/zetetos/gt-telemetry
            - golang.org/x/image
            - layeh.com/gopus
            - periph.io/x/conn/v3
            - periph.io/x/host/v3
    lll:
      line-length: 180
    gomoddirectives:
      replace-allow-list:
        - github.com/bwmarrin/discordgo # temporary until voice fix is merged
    tagliatelle:
      case:
        rules:
          json: goPascal


formatters:
  default:
    enable:
      - gci
      - gofmt
      - gofumpt
      - goimports
      - golines  exclusions:
    # generated: lax
    # paths:
    #   - third_party$
    #   - builtin$
    #   - examples$

issues:
  exclude-use-default: false
  exlude:
    - path: _test.go
      linters:
        - mnd
