#######################################
#      GT-Pi configuration file       #
#######################################

# Base directory where the asset files are stored
assetDir: ./assets

# Gain level to be applied to audio output
audioOutGain: -12

# Loggin level (trace, debug, info, warn, error, fatal, panic, off)
logLevel: warn

# Display orientation in degrees (0, 90, 180, 270)
orientation: 0

# Enable Pimoroni Pirate Audio HAT features (true, false)
pirateAudioEnabled: false

# Display telemetry for replays (true) or only when racing live (false)
replayMode: false

# Telemetry data source (udp://<ip>:<port>, file://<path>/<file>.<gtr|gtz>)
source: udp://255.255.255.255:33739