[app]
# Base directory where the asset files are stored
assetDir = "/opt/simtezilo/assets"

# Log level (trace, debug, info, warn, error, fatal, panic, off)
logLevel = "warn"

[telemetry]
# Telemetry data source (udp://<ip>:<port>, file://<path>/<file>.<gtr|gtz>)
source = "udp://127.0.0.1:33739"

# Display telemetry for replays (true) or only when racing live (false)
replayHaptics = false

[synthesizer]
# Gain level to be applied to audio output.
masterGain = -14.5
chassisVolume = 100
gearRaceVolume = 100
gearStreetVolume = 50

# Audio sample rate. Lower values will result in lower latency. The hardware
# may also dictate the lowest sample rate that can be used.
sampleRateHz = 8000

# FIXME: add description
pulseExponent = 0.56

# FIXME: add description
pulseScaleAdjustment = 0.01851852

# Maximum output amplitude for haptics. Any value higher than 1 could result in clipping.
pulseMaxAmplitude = 0.98

# Minimum output frequency for haptics.
# Lower minimum values may be too muted to feel and higher values will result
# in a harsher ride.
pulseMinFrequencyHz = 24.5

# Maximum output frequency for haptics.
# Lower maximum values may not be harsh enough for large impacts and higher
# values may also not be harsh enough either. The value should be lower than
# the rolloff point of the amplifiers low pass filter.
pulseMaxFrequencyHz = 40

[hardware]
# Raspberry Pi HAT hardware to use for display and buttons.
# Supported hardware:
# none (default)
# pirateaudio: Pimoroni PirateAudio Line Out
# waveshare: Waveshare 14972 Display
model = "pirateaudio"

# Display orientation in degrees (0, 90, 180, 270).
displayOrientation = 0