[app]
# Language for the user interface.
# Supported languages: en, ja-jp
language = "en"

# Log level (trace, debug, info, warn, error, fatal, panic, off)
# logLevel = "warn"
logLevel = "info"

# Enable haptics during replays
replayMode = false
# replayMode = true

[telemetry]
# Telemetry data source (udp://<ip>:<port>, file://<path>/<file>.<gtr|gtz>)
source = "udp://255.255.255.255:33739"
# source = "file://opt/simtezilo/replays/spa-francorchamps-gr010.gtz"
# source = "file://opt/simtezilo/replays/spa-francorchamps-lexus-lc500.gtz"
# source = "file://opt/simtezilo/replays/trial-mountain-porsche-911-rsr-991-17.gtz"
# source = "file://opt/simtezilo/replays/mt-panorama-nissan-r92cp-89.gtz"
# source = "file://opt/simtezilo/replays/tilde.gtz"

[synthesizer]
# Gain level to be applied to audio output.
#masterGain = -17.75 # Pirate Audio line out 
masterGain = -7.0 # Pirate Audio headphone amp
#masterGain = -14.75 # Spotpear Game 1.3
gainIncrement = 0.25
chassisVolume = 100
gearShiftVolume = 95
gearShiftVolumeMinRace = 50
gearShiftVolumeMinStreet = 20

# Audio sample rate. Lower values will result in lower latency. The hardware
# may also dictate the lowest sample rate that can be used.
sampleRateHz = 8000

# Output the audio signal to to a wav file when defined.
# outputFile = "/tmp/simtezilo.wav"

# FIXME add description
jerkCurve = 210
jerkMax = 80
snapCurve = 460
snapMax = 48
dynamicGearShiftFeedback = true
dynamicGearShiftCurve = 150
dynamicGearShiftGforceMax = 1.0

algorithm = "sum"

# Maximum output amplitude for haptics. Any value higher than 1 could result in clipping.
pulseMaxAmplitude = 1.0

# Minimum output frequency for haptics.
# Lower minimum values may be too muted to feel and higher values will result
# in a harsher ride.
pulseMinFrequencyHz = 8

# Maximum output frequency for haptics.
# Lower maximum values may not be harsh enough for large impacts and higher
# values may also not be harsh enough either. The value should be lower than
# the rolloff point of the amplifiers low pass filter.
pulseMaxFrequencyHz = 60

[hardware]
# Raspberry Pi HAT hardware to use for display and buttons.
# Supported hardware:
# none (default)
# pirateaudio: Pimoroni PirateAudio
# spotpear: Spotpear RPi-1.3inch-MINI-LCD
# waveshare: Waveshare 1.3inch LCD HAT
model = "pirateaudio"

# Display orientation in degrees (0, 90, 180, 270).
displayOrientation = 0
