[app]
# Log level (trace, debug, info, warn, error, fatal, panic, off)
# logLevel = "warn"
logLevel = "info"

# Enable haptics during replays
replayMode = false
# replayMode = true

[telemetry]
# Telemetry data source (udp://<ip>:<port>, file://<path>/<file>.<gtr|gtz>)
source = "udp://255.255.255.255:33739"
# source = "file://opt/simtezilo/replays/spa-francorchamps-gr010.gtz"
# source = "file://opt/simtezilo/replays/spa-francorchamps-lexus-lc500.gtz"
# source = "file://opt/simtezilo/replays/trial-mountain-porsche-911-rsr-991-17.gtz"
# source = "file://opt/simtezilo/replays/mt-panorama-nissan-r92cp-89.gtz"
# source = "file://opt/simtezilo/replays/tilde.gtz"

[synthesizer]
# Gain level to be applied to audio output.
masterGain = -7.5
gainIncrement = 0.25
chassisVolume = 100
gearVolume = 100
gearVolumeMinRace = 50
gearVolumeMinStreet = 20

# Audio sample rate. Lower values will result in lower latency. The hardware
# may also dictate the lowest sample rate that can be used.
sampleRateHz = 8000

# Output signal to file
outputFile = "/tmp/simtezilo.wav"

# FIXME add description
jerkProfile = 7
jerkExponent = 210
jerkMax = 80
snapProfile = 5
snapExponent = 462
snapMax = 48
gearExp = 150
gearMax = 1.0

algorithm = "sum"

# jerk exponent, jerk scale, snap exponent, snap scale
profiles = [
    { JerkExponent = 475, JerkMax = 80, SnapExponent = 600, SnapMax = 48 }, # 1
    { JerkExponent = 450, JerkMax = 80, SnapExponent = 555, SnapMax = 48 }, # 2
    { JerkExponent = 425, JerkMax = 80, SnapExponent = 510, SnapMax = 48 }, # 3
    { JerkExponent = 400, JerkMax = 80, SnapExponent = 470, SnapMax = 48 }, # 4
    { JerkExponent = 375, JerkMax = 80, SnapExponent = 420, SnapMax = 48 }, # 5
    { JerkExponent = 350, JerkMax = 80, SnapExponent = 380, SnapMax = 48 }, # 6
    { JerkExponent = 325, JerkMax = 80, SnapExponent = 335, SnapMax = 48 }, # 7
    { JerkExponent = 300, JerkMax = 80, SnapExponent = 390, SnapMax = 48 }, # 8
    { JerkExponent = 275, JerkMax = 80, SnapExponent = 345, SnapMax = 48 }, # 9
    { JerkExponent = 250, JerkMax = 80, SnapExponent = 200, SnapMax = 48 }, # 10
]

# Maximum output amplitude for haptics. Any value higher than 1 could result in clipping.
pulseMaxAmplitude = 0.98

# Minimum output frequency for haptics.
# Lower minimum values may be too muted to feel and higher values will result
# in a harsher ride.
pulseMinFrequencyHz = 12

# Maximum output frequency for haptics.
# Lower maximum values may not be harsh enough for large impacts and higher
# values may also not be harsh enough either. The value should be lower than
# the rolloff point of the amplifiers low pass filter.
pulseMaxFrequencyHz = 60

# Signal equaliser levels from 10Hz to 40Hz in 1Hz steps.
eq = [
    2.00, 2.00, 1.90, 1.80, 1.70, 1.60, 1.50, 1.45, 1.40, 1.35, # 10-19Hz
    1.30, 1.25, 1.20, 1.15, 1.10, 1.05, 1.00, 1.00, 1.00, 1.00, # 20-29Hz
    1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, # 30-39Hz
    1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, # 40-49Hz
]

[hardware]
# Raspberry Pi HAT hardware to use for display and buttons.
# Supported hardware:
# none (default)
# pirateaudio: Pimoroni PirateAudio Line Out
# waveshare: Waveshare 14972 Display
model = "pirateaudio"

# Display orientation in degrees (0, 90, 180, 270).
displayOrientation = 0
