[app]
# Base directory where the asset files are stored
# assetDir = "/opt/simtezilo/assets"
assetDir = "/Users/vaughan/Workspace/github.com/vwhitteron/simtelizo-dev/assets"

# Log level (trace, debug, info, warn, error, fatal, panic, off)
# logLevel = "warn"
logLevel = "info"

# Enable haptics during replays
replayMode = false
# replayMode = true

[telemetry]
# Telemetry data source (udp://<ip>:<port>, file://<path>/<file>.<gtr|gtz>)
source = "udp://255.255.255.255:33739"
# source = "file://assets/replay/spa-francorchamps-lexus-lc500.gtz"
# source = "file://assets/replay/trial-mountain-porsche-911-rsr-991-17.gtz"
# source = "file://assets/replay/mt-panorama-nissan-r92cp-89.gtz"

[synthesizer]
# Gain level to be applied to audio output.
masterGain = -14.5
gainIncrement = 0.25
chassisVolume = 100
gearRaceVolume = 100
gearStreetVolume = 60

# Audio sample rate. Lower values will result in lower latency. The hardware
# may also dictate the lowest sample rate that can be used.
sampleRateHz = 8000

# Exponent applied to the jerk value. Effectively compresses the dynamic range of the
# value to more closely fit the output capabilities of the transducer.
pulseExponent = 0.46

# Reduction scale applied to the compressed jerk value. The result of the dynamic range
# reduction will still be orders of magnitude higher than can be output to the transducer.
# Ideally the output should feel like a natural match to feedback from the steering wheel
# as well as visual movements of the chassis.
pulseScaleAdjustment = 0.0353

# FIXME add description
forceProfile = 5
grainProfile = 5

# jerk exponent, jerk scale, snap exponent, snap scale
profiles = [
    { jerkExponent = 0.475, jerkScale = 0.01748, snapExponent = 0.475, snapScale = 0.00455 },
    { jerkExponent = 0.450, jerkScale = 0.02168, snapExponent = 0.450, snapScale = 0.00618 },
    { jerkExponent = 0.425, jerkScale = 0.02681, snapExponent = 0.425, snapScale = 0.00838 },
    { jerkExponent = 0.400, jerkScale = 0.03312, snapExponent = 0.400, snapScale = 0.01137 },
    { jerkExponent = 0.375, jerkScale = 0.04098, snapExponent = 0.375, snapScale = 0.01543 },
    { jerkExponent = 0.350, jerkScale = 0.05077, snapExponent = 0.350, snapScale = 0.02093 },
    { jerkExponent = 0.325, jerkScale = 0.06280, snapExponent = 0.325, snapScale = 0.02840 },
    { jerkExponent = 0.300, jerkScale = 0.07768, snapExponent = 0.300, snapScale = 0.03853 },
    { jerkExponent = 0.275, jerkScale = 0.09614, snapExponent = 0.275, snapScale = 0.05228 },
    { jerkExponent = 0.250, jerkScale = 0.11895, snapExponent = 0.250, snapScale = 0.07094 },
]

# Maximum output amplitude for haptics. Any value higher than 1 could result in clipping.
pulseMaxAmplitude = 0.98

# Minimum output frequency for haptics.
# Lower minimum values may be too muted to feel and higher values will result
# in a harsher ride.
pulseMinFrequencyHz = 16

# Maximum output frequency for haptics.
# Lower maximum values may not be harsh enough for large impacts and higher
# values may also not be harsh enough either. The value should be lower than
# the rolloff point of the amplifiers low pass filter.
pulseMaxFrequencyHz = 60

# Signal equaliser levels from 10Hz to 40Hz in 1Hz steps.
eq = [
    2.00, 2.00, 1.90, 1.80, 1.70, 1.60, 1.50, 1.45, 1.40, 1.35, # 10-19Hz
    1.30, 1.25, 1.20, 1.15, 1.10, 1.05, 1.00, 1.00, 1.00, 1.00, # 20-29Hz
    1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, # 30-39Hz
    1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, # 40-49Hz
]

[hardware]
# Raspberry Pi HAT hardware to use for display and buttons.
# Supported hardware:
# none (default)
# pirateaudio: Pimoroni PirateAudio Line Out
# waveshare: Waveshare 14972 Display
model = "none"

# Display orientation in degrees (0, 90, 180, 270).
displayOrientation = 0