[app]
# Base directory where the asset files are stored
assetDir = "/opt/simtezilo/assets"

# Log level (trace, debug, info, warn, error, fatal, panic, off)
logLevel = "warn"

# Enable haptics during replays
replayMode = false

[telemetry]
# Telemetry data source (udp://<ip>:<port>, file://<path>/<file>.<gtr|gtz>)
source = "udp://255.255.255.255:33739"

[synthesizer]
# Gain level to be applied to audio output.
masterGain = -4.5
chassisVolume = 100
gearRaceVolume = 100
gearStreetVolume = 60

# Audio sample rate. Lower values will result in lower latency. The hardware
# may also dictate the lowest sample rate that can be used.
sampleRateHz = 8000

# Exponent applied to the jerk value. Effectively compresses the dynamic range of the
# value to more closely fit the output capabilities of the transducer.
pulseExponent = 0.46

# Reduction scale applied to the compressed jerk value. The result of the dynamic range
# reduction will still be orders of magnitude higher than can be output to the transducer.
# Ideally the output should feel like a natural match to feedback from the steering wheel
# as well as visual movements of the chassis.
pulseScaleAdjustment = 0.0353

# Maximum output amplitude for haptics. Any value higher than 1 could result in clipping.
pulseMaxAmplitude = 0.98

# Minimum output frequency for haptics.
# Lower minimum values may be too muted to feel and higher values will result
# in a harsher ride.
pulseMinFrequencyHz = 20

# Maximum output frequency for haptics.
# Lower maximum values may not be harsh enough for large impacts and higher
# values may also not be harsh enough either. The value should be lower than
# the rolloff point of the amplifiers low pass filter.
pulseMaxFrequencyHz = 60

# Signal equaliser levels from 10Hz to 40Hz in 1Hz steps.
eq = [
    2.00, 2.00, 1.90, 1.80, 1.70, 1.60, 1.50, 1.45, 1.40, 1.35, # 10-19Hz
    1.30, 1.25, 1.20, 1.15, 1.10, 1.05, 1.00, 1.00, 1.00, 1.00, # 20-29Hz
    1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, # 30-39Hz
    1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, # 40-49Hz
]

[hardware]
# Raspberry Pi HAT hardware to use for display and buttons.
# Supported hardware:
# none (default)
# pirateaudio: Pimoroni PirateAudio Line Out
# waveshare: Waveshare 14972 Display
model = "pimoroni"

# Display orientation in degrees (0, 90, 180, 270).
displayOrientation = 0