[app]
# Base directory where the asset files are stored
# assetDir = "/opt/simtezilo/assets"
assetDir = "/Users/vaughan/Workspace/github.com/vwhitteron/simtelizo-dev/assets"

# Log level (trace, debug, info, warn, error, fatal, panic, off)
# logLevel = "warn"
logLevel = "info"

# Enable haptics during replays
# replayMode = false
replayMode = true

[telemetry]
# Telemetry data source (udp://<ip>:<port>, file://<path>/<file>.<gtr|gtz>)
# source = "udp://255.255.255.255:33739"
# source = "file://assets/replay/spa-francorchamps-gr010.gtz"
# source = "file://assets/replay/spa-francorchamps-lexus-lc500.gtz"
source = "file://assets/replay/trial-mountain-porsche-911-rsr-991-17.gtz"
# source = "file://assets/replay/mt-panorama-nissan-r92cp-89.gtz"

[synthesizer]
# Gain level to be applied to audio output.
masterGain = -4.5
gainIncrement = 0.25
chassisVolume = 100
gearRaceVolume = 100
gearStreetVolume = 35

# Audio sample rate. Lower values will result in lower latency. The hardware
# may also dictate the lowest sample rate that can be used.
sampleRateHz = 8000

# Output signal to file
outputFile = "/tmp/simtezilo.wav"

# FIXME add description
forceProfile = 6
forceMax = 80
grainProfile = 6
grainMax = 48

algorithm = "rss"

# jerk exponent, jerk scale, snap exponent, snap scale
profiles = [
    { jerkExponent = 0.475, jerkScale = 0.01748, snapExponent = 0.600, snapScale = 0.00455 }, # 1
    { jerkExponent = 0.450, jerkScale = 0.02168, snapExponent = 0.556, snapScale = 0.00618 }, # 2
    { jerkExponent = 0.425, jerkScale = 0.02681, snapExponent = 0.511, snapScale = 0.00838 }, # 3
    { jerkExponent = 0.400, jerkScale = 0.03312, snapExponent = 0.467, snapScale = 0.01137 }, # 4
    { jerkExponent = 0.375, jerkScale = 0.04098, snapExponent = 0.422, snapScale = 0.01543 }, # 5
    { jerkExponent = 0.350, jerkScale = 0.05077, snapExponent = 0.378, snapScale = 0.02093 }, # 6
    { jerkExponent = 0.325, jerkScale = 0.06280, snapExponent = 0.333, snapScale = 0.02840 }, # 7
    { jerkExponent = 0.300, jerkScale = 0.07768, snapExponent = 0.289, snapScale = 0.03853 }, # 8
    { jerkExponent = 0.275, jerkScale = 0.09614, snapExponent = 0.244, snapScale = 0.05228 }, # 9
    { jerkExponent = 0.250, jerkScale = 0.11895, snapExponent = 0.200, snapScale = 0.07094 }, # 10
]

# Maximum output amplitude for haptics. Any value higher than 1 could result in clipping.
pulseMaxAmplitude = 0.98

# Minimum output frequency for haptics.
# Lower minimum values may be too muted to feel and higher values will result
# in a harsher ride.
pulseMinFrequencyHz = 4

# Maximum output frequency for haptics.
# Lower maximum values may not be harsh enough for large impacts and higher
# values may also not be harsh enough either. The value should be lower than
# the rolloff point of the amplifiers low pass filter.
pulseMaxFrequencyHz = 60

# Signal equaliser levels from 10Hz to 40Hz in 1Hz steps.
eq = [
    2.00, 2.00, 1.90, 1.80, 1.70, 1.60, 1.50, 1.45, 1.40, 1.35, # 10-19Hz
    1.30, 1.25, 1.20, 1.15, 1.10, 1.05, 1.00, 1.00, 1.00, 1.00, # 20-29Hz
    1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, # 30-39Hz
    1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, # 40-49Hz
]

[hardware]
# Raspberry Pi HAT hardware to use for display and buttons.
# Supported hardware:
# none (default)
# pirateaudio: Pimoroni PirateAudio Line Out
# waveshare: Waveshare 14972 Display
model = "none"

# Display orientation in degrees (0, 90, 180, 270).
displayOrientation = 0