[app]
assetDir = "c:\\Users\\MyUser\\Simtezilo\\assets"
# assetDir = "/Users/myuser/Simtezilo/assets"
logLevel = "warn"
replayMode = false
# replayMode = true

[telemetry]
source = "udp://255.255.255.255:33739"
# source = "file://replay.gtz"

[synthesizer]
masterGain = -14.0
chassisVolume = 100
gearRaceVolume = 100
gearStreetVolume = 60
sampleRateHz = 32000
forceProfile = 5
grainProfile = 5
