package synthesizer

import (
	"math"
	"testing"
	"time"

	"github.com/vwhitteron/simtezilo-dev/app/calibrator"
)

// mockMixer implements MixerInterface for testing.
// When calibration is enabled, it generates a sine wave in MixToMaster.
type mockMixer struct {
	calibrator  calibrator.Calibrator
	sampleRate  int
	phase       float64
	lastSamples []float64 // samples generated by MixToMaster
}

func (m *mockMixer) MixToMaster(length int) {
	m.lastSamples = make([]float64, length)

	if m.calibrator != nil && m.calibrator.IsEnabled() {
		freq := m.calibrator.GetFrequency()
		gainDB := m.calibrator.GetGain()
		gain := GainToPowerRatio(gainDB)

		for i := range m.lastSamples {
			m.lastSamples[i] = math.Sin(m.phase) * gain
			m.phase += 2 * math.Pi * freq / float64(m.sampleRate)

			if m.phase > 2*math.Pi {
				m.phase -= 2 * math.Pi
			}
		}
	}
}

func (m *mockMixer) ReadChannel(_ string, length int) []float64 {
	if len(m.lastSamples) == 0 {
		return make([]float64, length)
	}

	return m.lastSamples
}

func (m *mockMixer) AddChannel(_ string, _ float64) error {
	return nil
}

func (m *mockMixer) GetChannelGain(_ string) (float64, error) {
	return 0, nil
}

func (m *mockMixer) SetChannelGain(_ string, _ float64) error {
	return nil
}

func (m *mockMixer) GetChannelPowerRatio(_ string) (float64, error) {
	return 1, nil
}

func (m *mockMixer) WriteChannel(_ string, _ []float64, _ float64, _ int, _ bool) error {
	return nil
}

func (m *mockMixer) ClearChannelBuffer(_ string) {}

func (m *mockMixer) ClearBuffers() {}

func (m *mockMixer) InspectChannelBuffer(_ string, _ int, _ int) []float64 {
	return nil
}

func (m *mockMixer) GetBufferCapacity() int {
	return 0
}

func (m *mockMixer) FadeIn(_ time.Duration) {}

func (m *mockMixer) SetFader(_ float64) {}

func (m *mockMixer) ResetSineWavePhase() {}

func (m *mockMixer) Close() {}

func (m *mockMixer) GetChannelMute(_ int) bool {
	return false
}

func (m *mockMixer) GetMasterMute() bool {
	return false
}

func (m *mockMixer) SetSilenced(bool) {}

// mockCalibrator implements CalibratorInterface for testing.
type mockCalibrator struct {
	enabled   bool
	frequency float64
	gain      float64
	channel   calibrator.OutputChannel
}

func (c *mockCalibrator) IsEnabled() bool {
	return c.enabled
}

func (c *mockCalibrator) IsStopping() bool {
	return false
}

func (c *mockCalibrator) GetFrequency() float64 {
	return c.frequency
}

func (c *mockCalibrator) GetGain() float64 {
	return c.gain
}

func (c *mockCalibrator) GetChannel() calibrator.OutputChannel {
	return c.channel
}

func (c *mockCalibrator) GetSweepFrequency() float64 {
	return c.frequency
}

func (c *mockCalibrator) ConfirmStopped() {}

func TestStreamer_CalibrationModeOutputsSignal(t *testing.T) {
	t.Parallel()

	cal := &mockCalibrator{
		enabled:   true,
		frequency: 50, // 50 Hz test tone
		gain:      0,  // 0 dB (max)
		channel:   calibrator.OutputChannelBoth,
	}

	mixer := &mockMixer{
		calibrator: cal,
		sampleRate: 8000,
	}

	synth := &Synthesizer{
		calibrator: cal,
		mixer:      mixer,
		sampleRate: 8000,
	}
	streamer := &Streamer{synth: synth}

	samples := make([][2]float64, 100)

	n, ok := streamer.Stream(samples)
	if !ok || n != len(samples) {
		t.Fatalf("Stream() failed: ok=%v n=%d", ok, n)
	}

	// Check that at least one output sample is nonzero
	anyNonZero := false

	for _, s := range samples {
		if math.Abs(s[0]) > 1e-6 || math.Abs(s[1]) > 1e-6 {
			anyNonZero = true

			break
		}
	}

	if !anyNonZero {
		t.Error("Calibration mode did not output any signal (all zeros)")
	}
}
